version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - cd API
      - npm install
  build:
    commands:
      - echo Build started
      - npm run node
artifacts:
  files:
    - package.json
    - package-lock.json
    - node_modules/**/*
