version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - cd API
      - npm install
  build:
    commands:
      - echo Build started
      - cd API
      - node index.js
artifacts:
  files:
    - API/package.json
    - API/package-lock.json
    - API/node_modules/**/*
